### ISSUE TITLE
how to connect a computer to the brick? by USB?

### ISSUE THREAD

**Issue by UVCSzb** [jgraef/aNXT#3]
nxtnet_cli_connect is used to connect a brick by USB?

**Comment by jgraef** [comment]
nxtnet_\* is the network layer of aNXT - usually you don't have to use it. nxtnet_cli_connect connects to the aNXT daemon. To connect a brick via USB, just run nxtd and plug it in. To use the brick, use nxt_open or nxt_open_net.

Also this is not an issue.
